### ISSUE TITLE
running with timeout should be default

### ISSUE THREAD

**Issue by MartinNowak** [CyberShadow/DustMite#31]
I'm too often running into infinite loops, so I think a timeout should be enabled by default, rather than requiring another command.
Something like a minute or 30s would be a good default value.

https://github.com/CyberShadow/DustMite/wiki/Running-commands-with-a-timeout

**Comment by timotheecour** [comment]
instead of a fixed timeout, how about:
1) measure the time it takes for the input command to return, say T
2) for each reduction attempt, timeout after k*T (eg k=1.5)
Reductions should decrease time, not increase.
This could be a default option, overridable with --no-default-timeout

**Comment by MartinNowak** [comment]
Good idea @timotheecour.

**Comment by CyberShadow** [comment]
Re-implementing `timeout (1)` is not trivial because it needs to kill the entire process tree (otherwise you may very quickly end up with run-away child DMD processes eating all CPU, spawned in turn by killed dub or rdmd instances). Phobos doesn't have the cross-platform primitives for this, and I'm not even sure the OS declarations for the relevant APIs are in Druntime, e.g. no `CreateToolhelp32Snapshot` for Windows and I'm not even sure there's a cross-platform way to do it on POSIX (do you read `/proc`? do you parse the output of `ps`?).

**Comment by CyberShadow** [comment]
Closing until someone can come up with a concrete implementation strategy.
