### ISSUE TITLE
make testsuite run on posix and add CI

### ISSUE THREAD

**Issue by MartinNowak** [CyberShadow/DustMite#36]
It would great to make the tests run on any platform so I can add it to https://github.com/MartinNowak/project_tester.
It would also allow to enable CI.

**Comment by CyberShadow** [comment]
All that's needed is to translate all `test.cmd` files to an equivalent `test.sh`. I think we need both for as long as DMD can't use the MinGW toolchain on Windows.

But I think it doesn't make much sense to run the test suite automatically, because it only tests the reduction logic. The way to use it is you run it after changes in DustMite logic and inspect the git diff for any regressions (the reduction logs and results are also versioned in the repository).

**Comment by MartinNowak** [comment]
My main focus is on testing different dmd releases, so automatic testing makes a lot of sense (and it always does in general).

**Comment by CyberShadow** [comment]
Well, OK, I won't disagree, but out of curiosity, how would Dustmite's test suite help test DMD releases?

**Comment by MartinNowak** [comment]
One thing I learnt from 2.068.1 is that too few people actually test our betas, hence I setup a Jenkins to test many projects https://github.com/MartinNowak/project_teste, and I'd like to add dustmite.

**Comment by CyberShadow** [comment]
311e4577b1f62703a4c54b215d66128f4ae6b098

rdmd seems to hang randomly on Linux though, something about `TaskPool.parallel` threads never exiting.

> One thing I learnt from 2.068.1 is that too few people actually test our betas, hence I setup a Jenkins to test many projects https://github.com/MartinNowak/project_teste, and I'd like to add dustmite.

How can I add ae / Digger / DFeed? Must the projects be buildable with dub?

**Comment by CyberShadow** [comment]
CI added (Travis)
