### ISSUE TITLE
hashing/cache is too slow

### ISSUE THREAD

**Issue by MartinNowak** [CyberShadow/DustMite#37]
Dustmite spends way to much time computing MD5 sums only to find very few cache hits.
I'm currently reducing a dmd bug on vibe.d's source code w/ gdb as test runner (so it's expensive), and dustmite ss still a lot faster w/o cache.
One could try to compute hashes hierarchically, so one wouldn't to rehash a function that is used verbatim.

**Comment by CyberShadow** [comment]
Did you run dustmite with `--times`?

Cache hits occur more frequently with some other reduction strategies.

If you get my [ae library](https://github.com/CyberShadow/ae) and build Dustmite with `-version=HAVE_AE`, it will use MurmurHash3. We could add that to std.digest.

Another thing that could be done is to write to a static appender and then hash it all together, instead of by-piece hashing each lexical "token". This is already done with `HAVE_AE` (it uses a non-copyable optimized appender there).

**Comment by CyberShadow** [comment]
DustMite can be made to use https://github.com/D-Programming-Language/phobos/pull/3916 once that's in.

**Comment by CyberShadow** [comment]
OK, with `-j` hashing is definitely bottle-necking everything, so none of the above solutions would work. Instead we need per-element cached hashing (elements remember their hash and clear/recalculate it when they are modified).

**Comment by CyberShadow** [comment]
Fixed in f85acdfae6c5e6fd81af87d964114b8e43356f11
