### ISSUE TITLE
better heuristics to propose candidate reducations (to improve reduction speed)

### ISSUE THREAD

**Issue by timotheecour** [CyberShadow/DustMite#43]
during reduction, there are lots of obvious cases that take a while (in terms of iteratiosn) to remove, eg:
symbols not referenced.

these cases could be detected (using either a d parser or even using purely lexical analysis / word tokenization) to prioritize these reductions to be attempted before others

eg:
in following case, prioritize removing 
`int unused_variable=0;`  or `void unused_function(){....}` to be attempted before the other ones

```
void fun(){
bar;
}

void bar();

int unused_variable=0;

void unused_function(){....}
```

likewise with unused modules, etc

**Comment by CyberShadow** [comment]
No. DustMite is intentionally very dumb in its understanding of D syntax. Making it smarter will make it buggier and unable to reduce test cases as well.

DustMite already tries to remove things starting from the bottom, because declaration usually (and unconditionally in case of local symbols) precedes usage.

**Comment by timotheecour** [comment]
the suggestion i was making would only change the order in which candidate reductions are proposed, shouldn't affect correctness.

reductions take a lot of time when you have to track down a bug in a large project with tons of files

**Comment by CyberShadow** [comment]
> shouldn't affect correctness

Any increase in complexity risks affecting correctness.

DustMite currently does do some clever things in order to reduce e.g. import lists. I've introduced a few bugs when implementing those, which resulted in DustMite crashing when attempting to reduce large code bases. And of course, you can't reduce those codebases using DustMite because DustMite is broken. I had to revert to older versions or do it by hand to reduce the test cases.

> reductions take a lot of time

Yes. With any amount of optimizations, large code bases will take time to reduce. But starting a DustMite reduction shouldn't mean that you have to stop working on everything. Leave it aside and work on something else.

> eg: symbols not referenced

DustMite should already remove all (unused) declarations in one or two tests. Do you have an example where it doesn't?

**Comment by timotheecour** [comment]
>> DustMite should already remove all (unused) declarations in one or two tests. Do you have an example where it doesn't?

I see many Rejects [No] happening before dustmite attempts to remove an an-referenced function

if that's unexpected i can show some example.

seems like a simple enough heuristic.

**Comment by CyberShadow** [comment]
> I see many Rejects [No] happening before dustmite attempts to remove an an-referenced function

You can use `--dump` or `--trace` to be sure.

DustMite arranges everything into a binary tree, so a few negative results are normal at the beginning. This helps to quickly remove large unused portions of code.

> seems like a simple enough heuristic.

I'm looking forward to your pull request, then :)

**Comment by timotheecour** [comment]
>> DustMite arranges everything into a binary tree,

is there some provision to try to make the tree balanced?

eg:
suppose at top level we have 4 functions at module level:
fun1 fun2 fun3 fun4

will the tree be balanced or 1-sided [fun1 [fun2 [fun3 fun4]]] ?

**Comment by CyberShadow** [comment]
No, it should be evenly balanced for declarations on the same level.

Again, you can check the internal representation for yourself using `-dump`.
