### ISSUE TITLE
Information about strategies

### ISSUE THREAD

**Issue by John-Colvin** [CyberShadow/DustMite#54]
Dustmite has multiple different strategies, but no information about which would be better in what circumstances.

**Comment by CyberShadow** [comment]
> which would be better in what circumstances.

I actually don't *really* know either.

What I did was implement a whole bunch of them off the top of my head, pick a moderately sized reduction, run it through all strategies (with `--cache`), and pick the one that finished in fewest tests.

The only thing I theorize would be an improvement would be, if you're seeing a lot of successful reductions in a row, that probably means that Dustmite is trying to reduce some code that should be reduced at a higher level (i.e. it no longer participates in compilation), and one of the strategies that ascend (instead of just descend) might fare better (such as `careful`/`lookback`/`pingpong`).

**Comment by John-Colvin** [comment]
I'm imagining that maybe reductions of very large codebases where most of it can be quickly deleted would also benefit from strategies that ascend.
