### ISSUE TITLE
Omitting -q in grep can help on Windows.

### ISSUE THREAD

**Issue by veelo** [CyberShadow/DustMite#58]
Hi Vladimir,

I am making my first experiences with dustmite in a hunt to reduce an ICE, on Windows. I have two cents to share on this invaluable tool!

The error looks like this:
```
---
ERROR: This is a compiler bug.
Please report it via https://issues.dlang.org/enter_bug.cgi
with, preferably, a reduced, reproducible example and the information below.
DustMite (https://github.com/CyberShadow/DustMite/wiki) can help with the reduction.
---
DMD v2.088.0-dirty
predefs   Have_pias_d Have_derelict_gl3 Have_mir_algorithm Have_pascal2d_epcompat Have_derelict_util Have_mir_core DigitalMars Windows CRuntime_Microsoft CppRuntime_Microsoft LittleEndian D_Version2 all D_InlineAsm D_InlineAsm_X86 X86 Win32 assert D_ModuleInfo D_Exceptions D_TypeInfo D_HardFloat
binary    C:\D\dmd2\windows\bin\dmd.exe
version   v2.088.0-dirty
config    C:\D\dmd2\windows\bin\sc.ini
DFLAGS    -IC:\D\dmd2\windows\bin\..\..\src\phobos -IC:\D\dmd2\windows\bin\..\..\src\druntime\import -L/OPT:NOICF
---

object.Error@(0): Access Violation
----------------
0x006526B7
0x0065A151
0x00633651
0x006F6C18
0x0063438B
0x006F6C18
0x0063438B
```

Following the instructions on the wiki I was using a script like this:
```
dmd [...]  2>&1 | grep -qF "ERROR: This is a compiler bug"
```
But for each successful case, this caused the exception message at the end to appear in a popup box that had to be manually closed.

Just now I discovered that simply leaving out the `q` grep option causes the popups to stay away, and dustmite is happily reducing my code unattended. Output from dustmite is as before, there is no output from grep that leaks through to the console.

Thank you and be well,
Bastiaan.

**Comment by CyberShadow** [comment]
Thanks for sharing this information.

Showing the error message is a message box when it cannot be printed in full to the console is a relatively recent addition to Druntime, predated by Dustmite.

Because `grep -q` stops reading the input as soon as it finds the first match, it causes a broken pipe on the compiler end, which then resorts to showing the message in a message box. Without `-q`, grep reads all of its input in full.

A while ago, by default Dustmite did not redirect the output of the executed program, which means that you had to use -q or other redirection to prevent spamming the terminal with test scripts' output. I changed it to redirect by default, so -q is no longer as necessary.

I will update the wiki.

**Comment by CyberShadow** [comment]
https://github.com/CyberShadow/DustMite/wiki/Home/_compare/6eaa4cb380714debccdd08458f0f34fb648c3711

**Comment by veelo** [comment]
Thank you.

Again, I am mighty impressed. Starting out with a code base of 7.93 MB and no knowledge of how to use dustmite, one day later, dustmite completes with a result of only 1.95 KB. This I could manually reduce further to 10 lines. Very cool.

https://issues.dlang.org/show_bug.cgi?id=20247
