### ISSUE TITLE
Reduce false-positive results by replacing code with whitespace?

### ISSUE THREAD

**Issue by AndrejMitrovic** [CyberShadow/DustMite#59]
I believe currently Dustmite deletes code when it does its reduction? But that means we cannot have a test condition like `grep -F module.d(145): Error: No property info for 'abcd'` and instead have to search for something like: `grep -F "Error: No property info for 'abcd'` without the line number, which will bring out more false positives during reduction.

If instead Dustmite replaced code it wants to delete with whitespace characters, then the line numbers would be preserved, and we could have less false-positives this way.

What do you think?

**Comment by CyberShadow** [comment]
I think this is a great idea. It will increase I/O so probably will slow down reductions that don't need it, so, maybe a `--white-out` switch?

**Comment by CyberShadow** [comment]
It's a bit tricky because DustMite mutates its tree containing the reduced program on successful reductions by completely removing nodes. That would have to change (keep nodes but reduce non-whitespace characters with whitespace, and also don't try to reduce them again). An alternative would be to change how DustMite represents the reduced program in memory, e.g. make the tree immutable but keep a separate state which represents whether a node is removed or not. What complicates things is that there are other reduction types, like unwrap / concat, which do more complicated things than just remove nodes.

**Comment by CyberShadow** [comment]
Whee!
![](https://dump.thecybershadow.net/89759303221e7af8e07ce1d8103b928e/whiteout.gif)

**Comment by CyberShadow** [comment]
Implemented in 6746464fe8036342d0f657e11c442e9c24539085. It took me the better half of today to figure out the necessary alogrithm / data structure changes, but I'm pretty happy with the result :)

**Comment by AndrejMitrovic** [comment]
Amazing.

**Comment by Geod24** [comment]
Awesome, thanks!
